---
name: backtest_bay
channels: [conda-forge, r, nodefaults]
dependencies:
  - python ==3.12
  - pip >=21.1

  # Development dependencies
  - conda-lock
  - ipykernel
  - jupyterlab
  - pre-commit

  # Language agnostic template project dependencies
  - pytask >=0.5.0
  - pytask-latex >=0.4.2
  - pytask-parallel >=0.5.0
  - pytest
  - pytest-cov
  - pytest-xdist

  # Python template project dependencies
  - statsmodels
  - numpy
  - pandas >=2.2
  - plotly >=5.2.0,<6

  # Data dependencies
  - yfinance >=0.2.54

  # Install project
  - pip: [-e ., pdbp, kaleido]
